### ISSUE TITLE
fenwick logic: ArtifactSync will run forever and could get ahead of DeletedArtifactEventSync

### ISSUE THREAD

**Issue by pdowler** [opencadc/storage-inventory#160]
DeletedArtifactEvent(s) need to be processed before (new) Artifact(s) so that an overwrite (delete+put) at a storage site is processed correctly and does not cause a duplicate key failure (two artifacts with different ID but same URI).

**Comment by pdowler** [comment]
When a file is replaced at a site, this generates a
new DeletedArtifactEvent
new Artifact

The DeletedArtifactEvent need to be processed before the new Artifact because the Artifact has a uri that will conflict with the previous (deleted) Artifact.

In principle, it would also be good to process DeletedStorageLocationEvent(s).

must interleave event processing in timestamp order

**Comment by pdowler** [comment]
**Approach #1 -- set an upper bound on Entity.lastModified when harvesting**
In the `doit()` method:
- define max timestamp to harvest: `Date end = new Date();`
- pass `end` into each of the three sync methods and ultimately into the ADQL query: harvestState will usually impose a lower bound on lastModified and `end` will impose an upper bound

With this in place, syncArtifacts will not get ahead of syncDeletedArtifactEvents because they both query with the same `end` value.

**Comment by at88mph** [comment]
That is true that it would keep a consistent state.  We would lose audit information though as Fenwick still would not be harvesting _in the order they happened_.  Consider:

 * Artifact A1 gets added via file upload.  Site 2 gets the uploaded file.
 * Artifact A1 is replaced (DeletedArtifactEvent + New Artifact) within the same period (lower bound - upper bound).  Site 2 gets the replacement.
 * Site 1 runs Fenwick to pull the deltas in.

Because the DeletedArtifactEvents are all processed first, the initial add is lost to Site 1 (it never knows about it).  Would we need to preserve that somehow?

**Comment by pdowler** [comment]
There is no audit trail in the database content and no guarantee that all operations are executed in every site so yes: Site 1 would never know that a previous artifact ever existed. That does not stop site 1 and site 2 to reach (eventually) consistent state which is all that matters.
