### ISSUE TITLE
cadc-storage-adapter-fs clarification

### ISSUE THREAD

**Issue by zombiepig01** [opencadc/storage-inventory#495]
Hi Pat -- in the cadc-storage-adpater-fs documentation, you describe org.opencadc.inventory.storage.fs.OpaqueFileSystemStorageAdapter.bucketLength as a 'length', with 2^length directories being created.  Aren't you describing a directory tree **depth**, though?  The term bucket used elsewhere is very different than its use here, and seems a bit confusing.   

I guess the 'bucket' in this case is the traversal of the path to the nodes, so a file stored in a/0/f/ (directory tree depth of 3) has a 'bucket' of 'a0f'.

If the above is correct, I could provide an image making the transposition of length vs depth a bit more clear.

John

**Comment by pdowler** [comment]
I'm describing the length of the hex bucket string, which is equivalent to be the depth of directories. The mistake in the docs is that there are `16^length` dirs at the bottom level, so that many "buckets".  

Yes: the main thing is to convey that length == 3 means buckets like `a0f`, which is what you need to know when configuring tantar instances.

The fact that it is a depth of directory tree is just to explain what it does internally so a deployer can grok what it does and how to chose a length (because tantar validation has to list a whole bucket and hold it in memory so one is balancing memory consumption vs fs dir listing ops). I guess technically validation also holds (length-1) lists of intervening dirs (16 dirs each), but that's close enough to a constant that I didn't bother explaining it. Practically, length of 3-4 is good for most use cases, 1-2 for testing, ... I don't think I'd ever use 5.

I will fix the mistake.

**Comment by pdowler** [comment]
attempt to clarify in PR #493
